-- AXERLY modified 2026-09-23.
-- Word add-in conversations are intentionally separate from the web
-- assistant's chats/chat_messages tables. A client_document_id is generated by
-- the add-in and embedded in the .docx through Office document settings.

create table if not exists public.word_documents (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  client_document_id uuid not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, client_document_id)
);

create index if not exists idx_word_documents_user_updated
  on public.word_documents(user_id, updated_at desc);

create table if not exists public.word_chats (
  id uuid primary key default gen_random_uuid(),
  word_document_id uuid not null
    references public.word_documents(id) on delete cascade,
  user_id text not null,
  title text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_word_chats_document_updated
  on public.word_chats(word_document_id, updated_at desc);

create index if not exists idx_word_chats_user
  on public.word_chats(user_id);

create table if not exists public.word_chat_messages (
  id uuid primary key default gen_random_uuid(),
  chat_id uuid not null references public.word_chats(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content jsonb,
  files jsonb,
  workflow jsonb,
  citations jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_word_chat_messages_chat_created
  on public.word_chat_messages(chat_id, created_at);

-- Application data is reachable only through the axerly_app backend. RLS
-- and revoked browser grants provide defense in depth if a client is ever
-- accidentally pointed directly at Supabase.
revoke all on public.word_documents from public;
revoke all on public.word_chats from public;
revoke all on public.word_chat_messages from public;

grant select, insert, update, delete
  on public.word_documents, public.word_chats, public.word_chat_messages
  to axerly_app;
